### ISSUE TITLE
Footer scroll issue

### ISSUE THREAD

**Issue by csteinert** [csteinert/friends-of-gdic#13]
The footer is fixed so that it's always on the bottom of the screen, which is perfect I love it. Unfortunately, it has the potential to cut off the bottom of the list (on smaller screens, once the list gets long enough) in its current state.

In the below image, I created the test scenario by copy-pasting a bunch of `LI` elements to fill out the list, and then used the Inspector in Chrome to see if any of the elements were covered.

![scroll-bug](https://user-images.githubusercontent.com/1918353/31739062-a7611796-b41a-11e7-9762-2c66ed6bfef0.png)

There's a few different ways to fix this using just CSS, pick whichever one works best for you!

**Comment by gtkpr** [comment]
i can fix this for you. i've decided to participate in hacktoberfest and this would be my first ever contribution. anyways, let me know :D

**Comment by csteinert** [comment]
Fixed by @gtkpr, thanks!
