### ISSUE TITLE
Add info on how to clone a repo to the README

### ISSUE THREAD

**Issue by csteinert** [csteinert/friends-of-gdic#3]
It would be helpful to folks who are new to Git/GitHub if there was a bit more information in the README.md file about how to clone a repo to their computer and begin working on it. Written documentation or a link to an existing explanation would be great.

**Comment by anhelina** [comment]
Seems explanatory https://help.github.com/articles/cloning-a-repository// Should I add it to the readme.md?

**Comment by maryeb** [comment]
I am working through a Udacity tutorial on Git/GitHub that I really like. Would you like me to add the link to the readme.md - once I figure out how to do that?

**Comment by csteinert** [comment]
Both links will probably be helpful. I know it's useful for folks to see more than one explanation sometimes. You can both submit PRs for this issue! @maryeb @anhelina
