### ISSUE TITLE
Change the fonts

### ISSUE THREAD

**Issue by csteinert** [csteinert/friends-of-gdic#4]
I've picked out the two fonts I like. Link to them in `index.html` and set the correct styles in `styles.css`!

I would like the header fonts (`h1` and `h2`) to be in Patrick Hand SC:
https://fonts.google.com/specimen/Patrick+Hand+SC

And I would like the body text to be in Source Sans Pro: https://fonts.google.com/specimen/Source+Sans+Pro

**Comment by gtkpr** [comment]
i can fix this for you. i've decided to participate in hacktoberfest and this would be my first ever contribution. anyways, let me know :D

**Comment by csteinert** [comment]
Issue fixed in #23
