### ISSUE TITLE
Add spacing between list items.

### ISSUE THREAD

**Issue by csteinert** [csteinert/friends-of-gdic#7]
The list items (`<LI>`) elements are too close together, in my opinion:
<img width="184" alt="screenshot 2017-10-17 16 22 17" src="https://user-images.githubusercontent.com/1918353/31687516-7196f518-b357-11e7-9187-5adf7f2eeaa0.png">
Add some space between the `LI`s using CSS. (Margin? Padding? Your choice!)

**Comment by gtkpr** [comment]
i can fix this for you. i've decided to participate in hacktoberfest and this would be my first ever contribution. anyways, let me know :D

**Comment by csteinert** [comment]
PR pending (#24)
